---
- name: Wipe NVMe Drives by Serial Number
  hosts: proxmox
  become: true
  tasks:
    - name: Ensure parted is installed
      apt:
        name: parted
        state: present
        update_cache: yes
        
    - name: Map serial numbers to device paths
      set_fact:
        drives_to_wipe: >-
          {{
            ansible_facts.devices | dict2items
            | selectattr('value.serial', 'defined')
            | selectattr('value.serial', 'in', sp_nvme_serials)
            | map(attribute='key')
            | map('regex_replace', '^', '/dev/')
            | list
          }}

    - name: Debug matched drives
      debug:
        msg: "Found matches: {{ drives_to_wipe }}"

    - name: Fail if no drives were matched (Safety Check)
      fail:
        msg: "Could not find drives matching the serials provided!"
      when: drives_to_wipe | length == 0

    - name: Process drives found
      include_tasks: inner_wipe.yml
      loop: "{{ drives_to_wipe }}"
      loop_control:
        loop_var: current_drive
